# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-toml
    -   id: end-of-file-fixer
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.9.9"
    hooks:
    # Run the linter.
    -   id: ruff
        args: [--fix]
    -   id: ruff
        args: [--select, I, --fix]
    # Run the formatter.
    -   id: ruff-format
